import type { Metadata } from 'next';
import './globals.css';
import { Fira_Code } from 'next/font/google';
import AppLayout from '@/layouts/app.layout';
import { ThemeProvider } from '@/components/app/theme-provider';
import { NextIntlClientProvider } from 'next-intl';
import Sidebar from '@/components/app/sidebar';
import { Toaster } from '@/components/ui/sonner';

const firaCode = Fira_Code({
	variable: '--font-fira-code',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

type Props = {
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: Readonly<Props>) {
	// Ensure that the incoming `locale` is valid
	const { locale } = await params;

	return (
		<html lang={locale} className='dark' style={{ colorScheme: 'dark' }} suppressHydrationWarning>
			<body
				className={`${firaCode.variable} font-sans antialiased transition-colors duration-200 text-sm`}
			>
				<NextIntlClientProvider locale={locale}>
					<ThemeProvider
						attribute='class'
						defaultTheme='dark'
						enableSystem
						disableTransitionOnChange
					>
						<AppLayout>
							<div className='flex flex-1 grow overflow-hidden size-full'>
								<Sidebar />
								<div className='relative overflow-auto size-full'>{children}</div>
							</div>
						</AppLayout>
					</ThemeProvider>
				</NextIntlClientProvider>
				<Toaster />
				{/* Background effect */}
				<div className='grain-noise fixed inset-0 pointer-events-none opacity-30' />
			</body>
		</html>
	);
}
