import type { Metadata } from 'next';
import '../globals.css';
import { Fira_Code } from 'next/font/google';
import AppLayout from '@/layouts/app.layout';
import { ThemeProvider } from '@/components/app/theme-provider';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import { loadMessages } from '@/lib/i18n';
import Sidebar from '@/components/app/sidebar';

const firaCode = Fira_Code({
	variable: '--font-fira-code',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

type Props = {
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
};

export default async function LocaleLayout({ children, params }: Props) {
	// Ensure that the incoming `locale` is valid
	const { locale } = await params;
	if (!hasLocale(routing.locales, locale)) {
		notFound();
	}
	const messages = await loadMessages(locale, ['layout']);
	return (
		<html lang={locale} className='dark' style={{ colorScheme: 'dark' }} suppressHydrationWarning>
			<body
				className={`${firaCode.variable} font-sans antialiased transition-colors duration-200 text-sm`}
			>
				<NextIntlClientProvider locale={locale} messages={messages}>
					<ThemeProvider
						attribute='class'
						defaultTheme='dark'
						enableSystem
						disableTransitionOnChange
					>
						<AppLayout>
							<div className='flex flex-1 grow overflow-hidden size-full'>
								<Sidebar />
								<div className='relative overflow-auto size-full'>{children}</div>
							</div>
						</AppLayout>
					</ThemeProvider>
				</NextIntlClientProvider>

				{/* Background effect */}
				<div className='grain-noise fixed inset-0 pointer-events-none opacity-30' />
			</body>
		</html>
	);
}
